/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlPYP;
import controlador.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author AngelEduardo
 */
public class Frm_Principal extends javax.swing.JFrame {

    private ControlPYP ctrlpyp = new ControlPYP();

    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        initComponents();
        setResizable(false);
    }

    private void MostrarPYP() {
        if (!txtNroMatricula.getText().isEmpty()) {
            this.ctrlpyp.getPyp().setUltimoDigito(Integer.parseInt(txtNroMatricula.getText()));
            this.ctrlpyp.ObtenerPYP();
            txtPyP.setText(this.ctrlpyp.getPyp().getPYP());
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el número de matrícula del auto","Campo Obligatorio",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNroMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPyP = new javax.swing.JTextArea();
        btnCtrl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Días de la Semana que Aplica PYP:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 270, 17);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("CONTROL PYP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 220, 14);

        txtNroMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNroMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroMatriculaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNroMatricula);
        txtNroMatricula.setBounds(10, 90, 240, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese el Nro. de Matrícula del Vehiculo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 270, 17);

        txtPyP.setColumns(20);
        txtPyP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPyP.setRows(5);
        txtPyP.setEnabled(false);
        jScrollPane1.setViewportView(txtPyP);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 250, 100);

        btnCtrl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCtrl.setText("CONTROL");
        btnCtrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtrlActionPerformed(evt);
            }
        });
        jPanel1.add(btnCtrl);
        btnCtrl.setBounds(70, 120, 110, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 310);

        setSize(new java.awt.Dimension(283, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNroMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroMatriculaKeyTyped
        // TODO add your handling code here:
        Utilidades.ValidarSoloNumeros(evt);
    }//GEN-LAST:event_txtNroMatriculaKeyTyped

    private void btnCtrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtrlActionPerformed
        // TODO add your handling code here:
        this.MostrarPYP();
    }//GEN-LAST:event_btnCtrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                } catch (Exception e) {
                }
                new Frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCtrl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNroMatricula;
    private javax.swing.JTextArea txtPyP;
    // End of variables declaration//GEN-END:variables
}
